# Python Numpy Tutorial

https://cs231n.github.io/python-numpy-tutorial/#numpy

In [12]:
import numpy as np

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

## rank 1 array (unidimensional)

In [13]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a)
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
[1 2 3]
(3,)
1 2 3
[5 2 3]


## rank 2 array (2 dimensions)

In [14]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


## How to create arrays

In [15]:
print('Create an array of all zeros')
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print('\nCreate an array of all ones')
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

print('\nCreate a constant array')
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
print('\nCreate a 2x2 identity matrix')
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
print('\nCreate an array filled with random values')
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     

Create an array of all zeros
[[0. 0.]
 [0. 0.]]

Create an array of all ones
[[1. 1.]]

Create a constant array
[[7 7]
 [7 7]]

Create a 2x2 identity matrix
[[1. 0.]
 [0. 1.]]

Create an array filled with random values
[[0.48426767 0.04067375]
 [0.63139695 0.73591569]]


## Array indexing

### Slicing

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

(3, 4)
[[2 3]
 [6 7]]


In [17]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [18]:
print(a, a.shape)

print('\n[1, :] -> Rank 1 view of the second row')
row_r1 = a[1, :]    # Rank 1 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"

print('\n[1:2, :] -> Rank 2 view of the second row')
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"


[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)

[1, :] -> Rank 1 view of the second row
[5 6 7 8] (4,)

[1:2, :] -> Rank 2 view of the second row
[[5 6 7 8]] (1, 4)
