In [1]:
import pandas as pd

In [11]:
data = pd.DataFrame({'year': [2015, 2016, 2017, 2018, 2019, 2020],
                     'month': [2, 3, 4, 5, 6, 7],
                     'day': [4, 5, 6, 7, 8, 9]})

In [12]:
data

year  month  day
0  2015      2    4
1  2016      3    5
2  2017      4    6
3  2018      5    7
4  2019      6    8
5  2020      7    9

## pd.to_numpy()

In [19]:
data_numpy = data.to_numpy()
print(type(data_numpy))
print('\n', data_numpy)
print('\n', data_numpy[1:2,:])

<class 'numpy.ndarray'>

 [[2015    2    4]
 [2016    3    5]
 [2017    4    6]
 [2018    5    7]
 [2019    6    8]
 [2020    7    9]]

 [[2016    3    5]]


## numpy to df

In [21]:
df = pd.DataFrame(data_numpy)
df.columns = data.columns.values
df

year  month  day
0  2015      2    4
1  2016      3    5
2  2017      4    6
3  2018      5    7
4  2019      6    8
5  2020      7    9